package com.frankies.bootcamp.model;

public enum OnboardingState {
    AUTHENTICATED,
    STRAVA_PENDING,
    COMPETITION_PENDING,
    COMPETITION_STARTS_SOON,
    COMPETITION_SELECTION_REQUIRED,
    COMPETITION_HISTORY_ONLY,
    READY
}
